export const CREATE = 'create'
export const UPDATE = 'update'
export const COMPLETE = 'complete'
export const UNDO_COMPLETE = 'undo-complete'
export const DESTROY = 'destroy'
export const DESTROY_COMPLETED = 'destroy_completed'
